// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Game struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Image       sql.NullString `json:"image"`
	Link        sql.NullString `json:"link"`
}

type Play struct {
	IDGame int32       `json:"id_game"`
	IDUser int32       `json:"id_user"`
	State  interface{} `json:"state"`
	Rating interface{} `json:"rating"`
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
