// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Game struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
	Link        string `json:"link"`
	Custom      string `json:"custom"`
}

type Play struct {
	IDGame int32       `json:"id_game"`
	IDUser int32       `json:"id_user"`
	State  interface{} `json:"state"`
	Rating interface{} `json:"rating"`
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
