// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const averageGameRating = `-- name: AverageGameRating :one
SELECT avg(COALESCE(rating, 0))
FROM plays
WHERE id_game = $1
`

func (q *Queries) AverageGameRating(ctx context.Context, idGame int32) (float64, error) {
	row := q.db.QueryRowContext(ctx, averageGameRating, idGame)
	var avg float64
	err := row.Scan(&avg)
	return avg, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO game (name, description, image, link) 
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, image, link
`

type CreateGameParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Image       sql.NullString `json:"image"`
	Link        sql.NullString `json:"link"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Link,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Link,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, password)
VALUES ($1, $2)
RETURNING id, name, password
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}

const createUserPlaysGame = `-- name: CreateUserPlaysGame :one
INSERT INTO plays (id_game, id_user)
VALUES ($1, $2)
RETURNING id_game, id_user
`

type CreateUserPlaysGameParams struct {
	IDGame int32 `json:"id_game"`
	IDUser int32 `json:"id_user"`
}

type CreateUserPlaysGameRow struct {
	IDGame int32 `json:"id_game"`
	IDUser int32 `json:"id_user"`
}

func (q *Queries) CreateUserPlaysGame(ctx context.Context, arg CreateUserPlaysGameParams) (CreateUserPlaysGameRow, error) {
	row := q.db.QueryRowContext(ctx, createUserPlaysGame, arg.IDGame, arg.IDUser)
	var i CreateUserPlaysGameRow
	err := row.Scan(&i.IDGame, &i.IDUser)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM game
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const deleteUserPlaysGame = `-- name: DeleteUserPlaysGame :exec
DELETE FROM plays
WHERE id_game = $1 AND id_user = $2
`

type DeleteUserPlaysGameParams struct {
	IDGame int32 `json:"id_game"`
	IDUser int32 `json:"id_user"`
}

func (q *Queries) DeleteUserPlaysGame(ctx context.Context, arg DeleteUserPlaysGameParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPlaysGame, arg.IDGame, arg.IDUser)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, name, description, image, link 
FROM game
WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Link,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id
FROM users
WHERE name = $1 AND password = $2
`

type GetUserParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Name, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listGames = `-- name: ListGames :many
SELECT id, name, description, image, link
FROM game
ORDER BY name
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Image,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :exec
UPDATE game 
SET name = $2, description = $3, image = $4 ,  link = $5
WHERE id = $1
`

type UpdateGameParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Image       sql.NullString `json:"image"`
	Link        sql.NullString `json:"link"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Link,
	)
	return err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE plays 
SET rating = $3
WHERE id_game = $1 AND id_user = $2
`

type UpdateRatingParams struct {
	IDGame int32       `json:"id_game"`
	IDUser int32       `json:"id_user"`
	Rating interface{} `json:"rating"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateRating, arg.IDGame, arg.IDUser, arg.Rating)
	return err
}

const updateState = `-- name: UpdateState :exec
UPDATE plays
SET state = $3
WHERE id_game = $1 AND id_user = $2
`

type UpdateStateParams struct {
	IDGame int32       `json:"id_game"`
	IDUser int32       `json:"id_user"`
	State  interface{} `json:"state"`
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, updateState, arg.IDGame, arg.IDUser, arg.State)
	return err
}
